### ISSUE TITLE
Hello sample actual input thanks

### ISSUE THREAD

**Issue by scheung38** [nishants/family-tree#2]
```
$ npm install

$ npm start 

$ Person = "Drita"; Relative = "sons"
undefined

```
is this correct?

**Comment by nishant-birdeye** [comment]
It returns undefined if their is not relative by the name. Also you don't need to pass quote with values.

What you are looking for is : 
```
Person = Drita; Relation = Sons
```

**Comment by nishants** [comment]
It returns undefined if their is not relative by the name. Also you don't need to pass quote with values.

What you are looking for is : 
```
Person = Drita; Relation = Sons
```

**Comment by scheung38** [comment]
I see that the seed.json has json of few families:


```
  "families" : [
    {
      "husband": "Shan",
      "wife"   : "Anga",
      "sons"   : ["Ish", "Chit", "Vich"],
      "daughters" : ["Satya"]
    },
    {
      "husband": "Chit",
      "wife"   : "Ambi",
      "sons"   : ["Vrita", "Drita"],
      "daughters" : []
    },
```

But it is a list of various families? No grand-father/mother, uncles, cousins etc. Or do I need to progressively make them at run time to build a larger related family?

**Comment by nishants** [comment]
Idea here is to define a family tree using a set of nuclear families. Nuclear families consist of husband, wife, son and daughters. 

Seed.json defines the set of nuclear families in the tree. This data is used to construct the whole family tree at runtime (see addFamily here https://github.com/nishants/family-tree/blob/master/src/models/FamilyTree.js).

Each nuclear family is related to its parent family node if either husband or wife belong to parent family as son/daughter.

Algorithm to build a tree : 
1. create a root node (top nuclear family in tree).
2. for a new nuclear family, find if husband or wife belongs as son/daughter to an existing family and this family as child node to the parent family
3. keep doing two, till all families are added to the tree.

**Comment by nishants** [comment]
To find grandfather/uncles/cousins, we traverse the tree at runtime. Algorithms to find such relationships is defined here : https://github.com/nishants/family-tree/blob/master/src/Relationships.js

**Comment by scheung38** [comment]
Thanks nishants. So next time, I need to rebuild the whole family again using the nuclear set of unit of husband, wife, son and daughters before I could query for uncles, grandfather etc?

**Comment by nishants** [comment]
Yes. You can simply define the families in seeds.json and start querying.

**Comment by scheung38** [comment]
Which command to start build a family from nuclear family? I do not see the add commands:

```
Person=Drita;Relation=wife
Available Options :
paternaluncle, maternaluncle, paternalaunt, maternalaunt, sister-in-laws, brother-in-laws, cousins, father, mother, children, sons, daughters, brothers, sisters, granddaughter
>
```
